# -*- coding: utf-8 -*-
"""NewModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDFeG_MNiTptZWQNLqnMD2lHEQCuPScx
"""

import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
import seaborn as sns
import numpy as np

# Cargar el CSV
df = pd.read_csv("../data/processed/coca_cola_data.csv")

import pandas as pd

# Paso 1: Entrenar Random Forest
X = df[['avg_daily_max_min', 'precipitation', 'conteo_hospitales', 'conteo_escuelas_secundaria']]
y = df['sold_norm']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Predicciones RF
y_pred_rf = rf_model.predict(X_test)
y_pred_rf_series = pd.Series(y_pred_rf, index=X_test.index)

# Paso 2: Combinar predicciones
df_test = df.loc[X_test.index].copy()
y_pred_combined = 0.5 * df_test["pred_norm"] + 0.5 * y_pred_rf_series

# Paso 3: Entrenar modelo de corrección de error (en TRAIN)
df_train = df.loc[X_train.index].copy()
y_pred_rf_train = rf_model.predict(X_train)
y_pred_rf_train_series = pd.Series(y_pred_rf_train, index=X_train.index)
y_pred_combined_train = 0.5 * df_train["pred_norm"] + 0.5 * y_pred_rf_train_series

# Calcular errores en el conjunto de ENTRENAMIENTO
error_train = df_train["sold_norm"] - y_pred_combined_train

# Entrenar modelo para predecir el error
X_train_error = X_train.copy()
error_model = RandomForestRegressor(n_estimators=50, random_state=42, max_depth=5)
error_model.fit(X_train_error, error_train)

# Predecir el error en TEST
error_pred_test = error_model.predict(X_test)

# Ajustar predicciones en TEST usando el error predicho
df_test["pred_ajustada_combined"] = y_pred_combined + error_pred_test

# Evaluación
mse_combined = mean_squared_error(y_test, df_test["pred_ajustada_combined"])
r2_combined = r2_score(y_test, df_test["pred_ajustada_combined"])
mae_combined = mean_absolute_error(y_test, df_test["pred_ajustada_combined"])

print(f'MSE del modelo combinado: {mse_combined}')
print(f'R² del modelo combinado: {r2_combined}')
print(f'MAE combinado: {mae_combined:.4f}')

# Comparar con original
mae_original = mean_absolute_error(df_test["sold_norm"], df_test["pred_norm"])
mae_rf_only = mean_absolute_error(y_test, y_pred_rf)

print(f"\nMAE original (pred_norm): {mae_original:.4f}")
print(f"MAE Random Forest solo: {mae_rf_only:.4f}")
print(f"MAE combinado ajustado: {mae_combined:.4f}")

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import seaborn as sns
import numpy as np

# --- Asegurar que las columnas sean numéricas ---
df["sold_norm"] = pd.to_numeric(df["sold_norm"], errors="coerce")
df["pred_norm"] = pd.to_numeric(df["pred_norm"], errors="coerce")
df["avg_daily_max_min"] = pd.to_numeric(df["avg_daily_max_min"], errors="coerce")
df["precipitation"] = pd.to_numeric(df["precipitation"], errors="coerce")

# --- Calcular error ---
df["error"] = df["pred_norm"] - df["sold_norm"]

# --- Variables predictoras (X) y variable objetivo (y) ---
X = df[["avg_daily_max_min", "precipitation"]]
y = df["error"]

# --- División en entrenamiento y prueba ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- Entrenar modelo ---
modelo_multi = LinearRegression()
modelo_multi.fit(X_train, y_train)

# --- Predicciones ---
y_pred = modelo_multi.predict(X_test)

# --- Evaluación ---
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(" MODELO LLUVIA Y TEMP PROMEDIO ")
print(f"MSE (error cuadrático medio): {mse:.4f}")
print(f"R² (bondad del ajuste): {r2:.3f}")
print(f"Ecuación del modelo:")
print(f"error = ({modelo_multi.coef_[0]:.4f}) * temperatura + ({modelo_multi.coef_[1]:.4f}) * precipitación + ({modelo_multi.intercept_:.4f})")

# === VISUALIZACIÓN EN 2D (MAPA DE CALOR) ===

# Agrupar por intervalos para suavizar el ruido
df["temp_bin"] = pd.cut(df["avg_daily_max_min"], bins=20)
df["precip_bin"] = pd.cut(df["precipitation"], bins=10)

# Calcular promedio del error por celda
tabla_calor = df.groupby(["temp_bin", "precip_bin"])["error"].mean().unstack()

import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error
import numpy as np

# --- Predecir el error con el modelo entrenado ---
df["error_predicho"] = modelo_multi.predict(df[["avg_daily_max_min", "precipitation"]])

# --- Calcular nueva predicción ajustada ---
df["pred_ajustada"] = df["pred_norm"] - df["error_predicho"]

# --- Promedios semanales para suavizar la visualización ---
comparacion_semana = (
    df.groupby("week")[["sold_norm", "pred_norm", "pred_ajustada"]]
    .mean()
    .reset_index()
)

# --- Calcular métricas ---
mae_original = mean_absolute_error(df["sold_norm"], df["pred_norm"])
mae_ajustada = mean_absolute_error(df["sold_norm"], df["pred_ajustada"])
mejora = (1 - mae_ajustada/mae_original) * 100

# --- Gráfico comparativo estilo profesional ---
plt.figure(figsize=(16, 8))
plt.style.use('dark_background')

# Graficar las tres líneas
plt.plot(
    comparacion_semana["week"],
    comparacion_semana["sold_norm"],
    color="#00ff00",
    linewidth=2.5,
    alpha=0.9,
    label="Ventas reales (Sold_norm)"
)
plt.plot(
    comparacion_semana["week"],
    comparacion_semana["pred_norm"],
    color="#ff4444",
    linestyle="--",
    linewidth=2.5,
    alpha=0.9,
    label="Predicción original (Pred_norm)"
)
plt.plot(
    comparacion_semana["week"],
    comparacion_semana["pred_ajustada"],
    color="#6666ff",
    linestyle="-.",
    linewidth=2.5,
    alpha=0.9,
    label="Predicción ajustada (con modelo de error)"
)

# Configuración del gráfico
plt.xlabel("Semana", fontsize=13)
plt.ylabel("Valor normalizado promedio", fontsize=13)
plt.title("Comparación semanal: Ventas reales vs Predicción original vs Predicción ajustada",
          fontsize=15, pad=20)
plt.legend(loc='upper right', fontsize=11, framealpha=0.9)
plt.grid(True, alpha=0.3, linestyle='--')
plt.tight_layout()

# Añadir caja con métricas en la esquina superior izquierda
textstr = f'MAE Original: {mae_original:.4f}\nMAE Ajustado: {mae_ajustada:.4f}\nMejora: {mejora:.1f}%'
props = dict(boxstyle='round', facecolor='black', alpha=0.8, edgecolor='white', linewidth=1.5)
plt.text(0.02, 0.98, textstr, transform=plt.gca().transAxes, fontsize=11,
         verticalalignment='top', bbox=props, color='white', weight='bold')

plt.show()

# --- Evaluar mejora con métricas detalladas ---
print("\n" + "="*80)
print("COMPARATIVA DE ERRORES")
print("="*80)
print(f"MAE original: {mae_original:.4f}")
print(f"MAE ajustada: {mae_ajustada:.4f}")
print(f"Mejora relativa: {mejora:.2f}%")
print("="*80)

# --- Métricas adicionales ---
from sklearn.metrics import mean_squared_error, r2_score

rmse_original = np.sqrt(mean_squared_error(df["sold_norm"], df["pred_norm"]))
rmse_ajustada = np.sqrt(mean_squared_error(df["sold_norm"], df["pred_ajustada"]))
r2_original = r2_score(df["sold_norm"], df["pred_norm"])
r2_ajustada = r2_score(df["sold_norm"], df["pred_ajustada"])

print("\n" + "="*80)
print("MÉTRICAS ADICIONALES")
print("="*80)
print(f"{'Métrica':<20} {'Original':<15} {'Ajustado':<15} {'Mejora':<10}")
print("-"*80)
print(f"{'MAE':<20} {mae_original:<15.4f} {mae_ajustada:<15.4f} {mejora:>9.2f}%")
print(f"{'RMSE':<20} {rmse_original:<15.4f} {rmse_ajustada:<15.4f} {(1-rmse_ajustada/rmse_original)*100:>9.2f}%")
print(f"{'R²':<20} {r2_original:<15.4f} {r2_ajustada:<15.4f} {((r2_ajustada-r2_original)/r2_original)*100:>9.2f}%")
print("="*80)

# --- Análisis semanal ---
mae_semanal_original = mean_absolute_error(comparacion_semana["sold_norm"], comparacion_semana["pred_norm"])
mae_semanal_ajustada = mean_absolute_error(comparacion_semana["sold_norm"], comparacion_semana["pred_ajustada"])

print("\n" + "="*80)
print("ANÁLISIS SEMANAL (promedios)")
print("="*80)
print(f"MAE semanal original: {mae_semanal_original:.4f}")
print(f"MAE semanal ajustada: {mae_semanal_ajustada:.4f}")
print(f"Mejora semanal: {(1-mae_semanal_ajustada/mae_semanal_original)*100:.2f}%")
print("="*80)

# --- Tabla de ejemplo: primeras 10 semanas ---
print("\n" + "="*80)
print("MUESTRA: PRIMERAS 10 SEMANAS")
print("="*80)
print(f"{'Semana':<8} {'Real':<10} {'Pred_orig':<12} {'Pred_ajust':<12} {'Error_orig':<12} {'Error_ajust':<12}")
print("-"*80)

for idx, row in comparacion_semana.head(10).iterrows():
    error_orig = abs(row['sold_norm'] - row['pred_norm'])
    error_ajust = abs(row['sold_norm'] - row['pred_ajustada'])

    print(f"{row['week']:<8.0f} {row['sold_norm']:<10.4f} {row['pred_norm']:<12.4f} "
          f"{row['pred_ajustada']:<12.4f} {error_orig:<12.4f} {error_ajust:<12.4f}")

print("="*80)

# --- Agregar la predicción de Random Forest solo al df_test ---
df_test["pred_rf_only"] = y_pred_rf_series

# --- Agregar estación según la fecha ---
df_test["day"] = pd.to_datetime(df_test["day"])
def obtener_estacion(fecha):
    mes = fecha.month
    if 3 <= mes <= 5:
        return "Primavera"
    elif 6 <= mes <= 8:
        return "Verano"
    elif 9 <= mes <= 11:
        return "Otoño"
    else:
        return "Invierno"

df_test["estacion"] = df_test["day"].apply(obtener_estacion)

# --- Agregar por semana ---
df_test_weekly = df_test.groupby(['week', 'estacion']).agg({
    'sold_norm': 'mean',
    'pred_norm': 'mean',
    'pred_rf_only': 'mean',
    'pred_ajustada_combined': 'mean'
}).reset_index().sort_values('week')

# --- Calcular métricas ---
mae_original = mean_absolute_error(df_test["sold_norm"], df_test["pred_norm"])
mae_rf_only = mean_absolute_error(df_test["sold_norm"], df_test["pred_rf_only"])
mae_combined = mean_absolute_error(df_test["sold_norm"], df_test["pred_ajustada_combined"])

# --- Crear visualización con estaciones ---
plt.figure(figsize=(16, 8))
plt.style.use('dark_background')

# Colores de fondo por estación
colores_estaciones = {
    "Invierno": "#4b6cb7",
    "Primavera": "#81c784",
    "Verano": "#ffb74d",
    "Otoño": "#f57c00"
}

# Agregar franjas verticales según estación
for estacion, grupo in df_test_weekly.groupby("estacion"):
    xmin = grupo["week"].min()
    xmax = grupo["week"].max()
    plt.axvspan(xmin, xmax, color=colores_estaciones[estacion], alpha=0.15, label=f"{estacion}")

# Graficar líneas
plt.plot(df_test_weekly['week'], df_test_weekly['sold_norm'],
         label='Ventas reales (Sold_norm)', color='#00ff00', linewidth=2.5)
plt.plot(df_test_weekly['week'], df_test_weekly['pred_norm'],
         label='Predicción original (Pred_norm)', color='#ff4444', linestyle='--', linewidth=2.5)
plt.plot(df_test_weekly['week'], df_test_weekly['pred_rf_only'],
         label='Random Forest solo', color='#ff8800', linestyle=':', linewidth=2.5)
plt.plot(df_test_weekly['week'], df_test_weekly['pred_ajustada_combined'],
         label='Predicción ajustada (ensemble + corrección)', color='#6666ff', linestyle='-.', linewidth=2.5)

# --- Configuración general ---
plt.xlabel('Semana', fontsize=13)
plt.ylabel('Valor normalizado promedio', fontsize=13)
plt.title('Comparación semanal por estación: Ventas reales vs Modelos predictivos', fontsize=15, pad=20)

# Leyenda combinada
handles, labels = plt.gca().get_legend_handles_labels()
# Quitar duplicados de estaciones
unique = list(dict(zip(labels, handles)).items())
plt.legend([h for _, h in unique], [l for l, _ in unique],
           loc='upper right', fontsize=11, framealpha=0.9)

plt.grid(True, alpha=0.3, linestyle='--')

# Cuadro de métricas
textstr = (f'MAE Original: {mae_original:.4f}\n'
           f'MAE RF solo: {mae_rf_only:.4f}\n'
           f'Mejora vs Original: {(1-mae_combined/mae_original)*100:.1f}%\n'
           f'Mejora vs RF: {(1-mae_combined/mae_rf_only)*100:.1f}%')
props = dict(boxstyle='round', facecolor='black', alpha=0.8, edgecolor='white', linewidth=1.5)
plt.text(0.02, 0.98, textstr, transform=plt.gca().transAxes, fontsize=10,
         verticalalignment='top', bbox=props, color='white', weight='bold')

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error
import numpy as np

# --- Convertir fecha y agregar estación ---
df_test["day"] = pd.to_datetime(df_test["day"])
def obtener_estacion(fecha):
    mes = fecha.month
    if 3 <= mes <= 5:
        return "Primavera"
    elif 6 <= mes <= 8:
        return "Verano"
    elif 9 <= mes <= 11:
        return "Otoño"
    else:
        return "Invierno"

df_test["estacion"] = df_test["day"].apply(obtener_estacion)

# --- Agregar la predicción ajustada global (modelo de error simple) ---
df_test["error_predicho_global"] = modelo_multi.predict(df_test[["avg_daily_max_min", "precipitation"]])
df_test["pred_ajustada_global"] = df_test["pred_norm"] - df_test["error_predicho_global"]

# --- Promedios semanales por estación ---
df_test_weekly = (
    df_test.groupby(['week', 'estacion'])
    .agg({
        'sold_norm': 'mean',
        'pred_norm': 'mean',
        'pred_rf_only': 'mean',
        'pred_ajustada_global': 'mean'
    })
    .reset_index()
    .sort_values('week')
)

# --- Calcular métricas ---
mae_original = mean_absolute_error(df_test["sold_norm"], df_test["pred_norm"])
mae_rf_only = mean_absolute_error(df_test["sold_norm"], df_test["pred_rf_only"])
mae_global = mean_absolute_error(df_test["sold_norm"], df_test["pred_ajustada_global"])

# --- Crear visualización ---
plt.figure(figsize=(16, 8))
plt.style.use('dark_background')

# Colores de fondo por estación
colores_estaciones = {
    "Invierno": "#4b6cb7",
    "Primavera": "#81c784",
    "Verano": "#ffb74d",
    "Otoño": "#f57c00"
}

# Franjas verticales según estación
for estacion, grupo in df_test_weekly.groupby("estacion"):
    xmin = grupo["week"].min()
    xmax = grupo["week"].max()
    plt.axvspan(xmin, xmax, color=colores_estaciones[estacion], alpha=0.15, label=f"{estacion}")

# --- Curvas principales ---
plt.plot(df_test_weekly['week'], df_test_weekly['sold_norm'],
         label='Ventas reales (Sold_norm)', color='#00ff00', linewidth=2.5)
plt.plot(df_test_weekly['week'], df_test_weekly['pred_norm'],
         label='Predicción original', color='#ff4444', linestyle='--', linewidth=2.5)
plt.plot(df_test_weekly['week'], df_test_weekly['pred_rf_only'],
         label='Random Forest solo', color='#ff8800', linestyle='-', linewidth=2.5)
plt.plot(df_test_weekly['week'], df_test_weekly['pred_ajustada_global'],
         label='Ajuste global (modelo de error)', color='#bb86fc', linestyle='-', linewidth=2.5)

# --- Configuración general ---
plt.xlabel('Semana', fontsize=13)
plt.ylabel('Valor normalizado promedio', fontsize=13)
plt.title('Comparación semanal por estación: Ventas reales vs Modelos predictivos',
          fontsize=15, pad=20)

# Leyenda combinada (sin duplicados)
handles, labels = plt.gca().get_legend_handles_labels()
unique = list(dict(zip(labels, handles)).items())
plt.legend([h for _, h in unique], [l for l, _ in unique],
           loc='upper right', fontsize=11, framealpha=0.9)

plt.grid(True, alpha=0.3, linestyle='--')

# --- Cuadro de métricas ---
textstr = (
    f"MAE Original: {mae_original:.4f}\n"
    f"MAE RF solo: {mae_rf_only:.4f}\n"
    f"MAE Global (modelo error): {mae_global:.4f}\n"
    f"Mejora Global vs Original: {(1 - mae_global/mae_original)*100:.1f}%"
)
props = dict(boxstyle='round', facecolor='black', alpha=0.8, edgecolor='white', linewidth=1.5)
plt.text(0.02, 0.98, textstr, transform=plt.gca().transAxes, fontsize=10,
         verticalalignment='top', bbox=props, color='white', weight='bold')

plt.tight_layout()
plt.show()