# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ViJ7NypviV2m2FcHQpxicgWNxWEf_mHw
"""

df['day'] = pd.to_datetime(df['day'], errors='coerce')
n_obs = df['day'].nunique()
print("Fechas únicas (observaciones diarias):", n_obs)

import warnings; warnings.filterwarnings("ignore")
import pandas as pd, numpy as np, matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
from statsmodels.stats.diagnostic import acorr_ljungbox

# ==== CONFIG ====
CSV_PATH = "/content/coca_cola_data.csv"  # ajusta si es diferente
DATE_COL = "day"
TARGET   = "sold_norm"
MIN_OBS  = 300   # mínimo para CV decente
FREQ     = "D"   # diaria
SEASON   = 7     # semanal en diaria

# ==== LOAD ====
df = pd.read_csv(CSV_PATH)
df[DATE_COL] = pd.to_datetime(df[DATE_COL], errors="coerce")
df = df.dropna(subset=[DATE_COL]).sort_values(DATE_COL)

# Serie diaria agregada a nivel total (puedes segmentar después)
ts = df.groupby(DATE_COL)[TARGET].sum().asfreq(FREQ)
ts = ts.replace([np.inf, -np.inf], np.nan).ffill().bfill()

print(ts.shape, ts.index.min(), ts.index.max())
ts.tail()

from typing import List, Dict, Tuple
from dataclasses import dataclass

def metrics_dict(y_true, y_pred):
    y_true, y_pred = y_true.align(y_pred, join="inner")
    mae  = mean_absolute_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred) ** 0.5
    mape = (np.abs((y_true - y_pred) / np.maximum(1e-8, y_true))).mean() * 100
    return {"MAE": mae, "RMSE": rmse, "MAPE_%": mape}

def seasonal_naive(train, horizon, season=SEASON):
    idx = pd.date_range(train.index[-1] + pd.Timedelta(days=1), periods=horizon, freq=train.index.freq)
    preds = []
    for d in idx:
        prev = d - pd.Timedelta(days=season)
        preds.append(train.get(prev, train.iloc[-1]))
    return pd.Series(preds, index=idx, name="naive")

@dataclass
class FoldResult:
    fold: int
    start: pd.Timestamp
    end: pd.Timestamp
    metrics: Dict[str, float]
    pred: pd.Series

def rolling_origin_folds(series: pd.Series, n_folds: int, horizon: int, min_train: int) -> List[Tuple[pd.Series, pd.Series]]:
    """Genera (train, test) para CV temporal incremental."""
    folds = []
    n = len(series)
    # tamaño aproximado de paso
    step = max(1, (n - min_train - horizon) // max(1, (n_folds)))
    anchor = min_train
    for i in range(n_folds):
        train_end = anchor + i*step
        if train_end + horizon > n: break
        train = series.iloc[:train_end]
        test  = series.iloc[train_end:train_end + horizon]
        if len(train) >= min_train and len(test) == horizon:
            folds.append((train, test))
    return folds

from statsmodels.tsa.statespace.sarimax import SARIMAX

# Grilla pequeña pero informativa (ajústala si tienes tiempo)
sarima_grid = [
    ((1,1,1), (1,1,1,SEASON)),
    ((0,1,1), (0,1,1,SEASON)),
    ((1,1,0), (1,1,0,SEASON)),
]

def fit_forecast_sarima(train, horizon, order, seasonal_order):
    model = SARIMAX(train, order=order, seasonal_order=seasonal_order,
                    enforce_stationarity=False, enforce_invertibility=False)
    res = model.fit(disp=False)
    fc = res.get_forecast(steps=horizon)
    mean = fc.predicted_mean
    conf = fc.conf_int(alpha=0.20)  # 80% CI (ajústalo a 95% si prefieres)
    return mean, conf  # (pred, intervalos)

def tune_sarima_cv(series: pd.Series, n_folds=4, horizon=14, min_train=MIN_OBS):
    folds = rolling_origin_folds(series, n_folds, horizon, min_train)
    results = []
    for order, seas in sarima_grid:
        fold_metrics = []
        preds_all = []
        for k,(train,test) in enumerate(folds, start=1):
            pred, conf = fit_forecast_sarima(train, len(test), order, seas)
            m = metrics_dict(test, pred)
            fold_metrics.append(m)
            preds_all.append(pred.rename(f"fold{k}"))
        avg = pd.DataFrame(fold_metrics).mean().to_dict()
        results.append({"order":order, "seas":seas, "avg_metrics":avg, "folds":fold_metrics})
    # elige por MAPE
    best = sorted(results, key=lambda r: r["avg_metrics"]["MAPE_%"])[0]
    return best, results

from prophet import Prophet

# Grilla corta de Prophet: mode + weekly + changepoint_prior_scale
prophet_grid = [
    {"seasonality_mode":"additive", "weekly_seasonality":True,  "changepoint_prior_scale":0.05},
    {"seasonality_mode":"multiplicative", "weekly_seasonality":True, "changepoint_prior_scale":0.05},
    {"seasonality_mode":"multiplicative", "weekly_seasonality":True, "changepoint_prior_scale":0.2},
]

def fit_forecast_prophet(train, horizon, params):
    dfp = train.reset_index().rename(columns={train.index.name or "index":"ds", train.name or TARGET:"y"})
    m = Prophet(daily_seasonality=True,
                weekly_seasonality=params.get("weekly_seasonality", True),
                yearly_seasonality=False,
                seasonality_mode=params.get("seasonality_mode","additive"),
                changepoint_prior_scale=params.get("changepoint_prior_scale",0.05))
    m.fit(dfp)
    future = m.make_future_dataframe(periods=horizon, freq="D")
    fcst = m.predict(future).set_index("ds")
    pred = fcst["yhat"].iloc[-horizon:]
    # Prophet ya trae intervalos yhat_lower / yhat_upper
    conf = fcst[["yhat_lower","yhat_upper"]].iloc[-horizon:]
    return pred, conf

def tune_prophet_cv(series: pd.Series, n_folds=4, horizon=14, min_train=MIN_OBS):
    folds = rolling_origin_folds(series, n_folds, horizon, min_train)
    results = []
    for params in prophet_grid:
        fold_metrics = []
        for k,(train,test) in enumerate(folds, start=1):
            pred, conf = fit_forecast_prophet(train, len(test), params)
            m = metrics_dict(test, pred)
            fold_metrics.append(m)
        avg = pd.DataFrame(fold_metrics).mean().to_dict()
        results.append({"params":params, "avg_metrics":avg, "folds":fold_metrics})
    best = sorted(results, key=lambda r: r["avg_metrics"]["MAPE_%"])[0]
    return best, results

# Checamos que haya datos suficientes
assert len(ts) >= MIN_OBS + 14, "Pocos datos para CV; reduce MIN_OBS o el horizonte."

N_FOLDS = 4
H = 14  # horizonte final para evaluación holdout

# Split final (holdout al final para reporte)
train_full = ts.iloc[:-H]
test_final = ts.iloc[-H:]

# --- Tuning ---
best_sar, sar_search = tune_sarima_cv(ts, n_folds=N_FOLDS, horizon=H, min_train=MIN_OBS)
best_prp, prp_search = tune_prophet_cv(ts, n_folds=N_FOLDS, horizon=H, min_train=MIN_OBS)

print("Mejor SARIMA:", best_sar["order"], best_sar["seas"], best_sar["avg_metrics"])
print("Mejor Prophet:", best_prp["params"], best_prp["avg_metrics"])

# --- Entrenamiento final y predicción holdout ---
sar_pred, sar_ci = fit_forecast_sarima(train_full, H, best_sar["order"], best_sar["seas"])
prp_pred, prp_ci = fit_forecast_prophet(train_full, H, best_prp["params"])

# Ensemble promedio simple
ensemble_pred = (sar_pred + prp_pred) / 2

# Métricas holdout
sar_metrics = metrics_dict(test_final, sar_pred)
prp_metrics = metrics_dict(test_final, prp_pred)
ens_metrics = metrics_dict(test_final, ensemble_pred)
naive_pred  = seasonal_naive(train_full, H, season=SEASON)
naive_metrics = metrics_dict(test_final, naive_pred)

pd.DataFrame([
    {"Modelo":"SARIMA", **sar_metrics},
    {"Modelo":"Prophet", **prp_metrics},
    {"Modelo":"Ensemble", **ens_metrics},
    {"Modelo":"SeasonalNaive", **naive_metrics},
])

# Unimos intervalos 80% de cada modelo (Prophet trae 80/95; SARIMA 80% arriba).
# Para ensemble, aproximación: promedio de medias y promedio de bandas (simple).
ens_ci = pd.DataFrame({
    "lower": (sar_ci.iloc[:,-2].values + prp_ci["yhat_lower"].values) / 2 if "yhat_lower" in prp_ci else sar_ci.iloc[:,-2].values,
    "upper": (sar_ci.iloc[:,-1].values + prp_ci["yhat_upper"].values) / 2 if "yhat_upper" in prp_ci else sar_ci.iloc[:,-1].values,
}, index=sar_pred.index)

tail = min(120+H, len(ts))
plt.figure(figsize=(11,5))
ts.iloc[-tail:].plot(label="Real", linewidth=2, alpha=.8)
pd.concat([ts.iloc[-tail:-H], sar_pred]).plot(label="SARIMA")
pd.concat([ts.iloc[-tail:-H], prp_pred]).plot(label="Prophet")
pd.concat([ts.iloc[-tail:-H], ensemble_pred]).plot(label="Ensemble", linestyle="-.")
pd.concat([ts.iloc[-tail:-H], naive_pred]).plot(label="Naive", linestyle="--")

# bandas ensemble (80% aprox)
plt.fill_between(ens_ci.index, ens_ci["lower"], ens_ci["upper"], alpha=0.15, label="Ensemble CI ~80%")
plt.title(f"Predicción holdout (H={H} días) con CI")
plt.legend(); plt.tight_layout(); plt.show()

from statsmodels.stats.diagnostic import acorr_ljungbox

def residual_report(residuals: pd.Series, name="res"):
    r = residuals.dropna().copy()
    print(f"\n=== Residuals: {name} ===")
    print("Media:", float(r.mean()), "| Std:", float(r.std()))

    n = len(r)
    if n < 5:
        print(f"Serie de residuales muy corta (n={n}); se omite Ljung-Box.")
    else:
        # Definir lags de forma segura (no mayores que n-2)
        candidate_lags = [7, 14, 21]
        safe_lags = sorted(set([L for L in candidate_lags if 1 <= L <= max(1, n-2)]))
        if not safe_lags:
            print(f"No hay lags válidos para Ljung-Box con n={n}.")
        else:
            for L in safe_lags:
                try:
                    # auto_lag=False evita re-cálculos que causan conflictos de tamaño
                    lb = acorr_ljungbox(r, lags=L, return_df=True, auto_lag=False)
                    pval = float(lb["lb_pvalue"].iloc[-1])
                    print(f"Ljung-Box (lags={L}) p-value = {pval:.4f}")
                except Exception as e:
                    print(f"Ljung-Box (lags={L}) falló: {e}")

    # Errores por día de semana / mes (si el índice es datetime)
    if isinstance(r.index, pd.DatetimeIndex):
        df_tmp = r.to_frame("res")
        df_tmp["dow"] = df_tmp.index.dayofweek
        df_tmp["month"] = df_tmp.index.month
        mae_dow = df_tmp.groupby("dow")["res"].apply(lambda s: np.mean(np.abs(s))).round(2)
        mae_mon = df_tmp.groupby("month")["res"].apply(lambda s: np.mean(np.abs(s))).round(2)
        print("MAE por día de semana:\n", mae_dow.to_string())
        print("MAE por mes:\n", mae_mon.to_string())
    else:
        print("Índice no es datetime; se omite MAE por día y mes.")

residual_report(res_sar, "SARIMA")
residual_report(res_prp, "Prophet")
residual_report(res_ens, "Ensemble")

# 1) Reconstruimos predicciones a nivel día para comparar contra el “total” real por día.
pred_df = pd.DataFrame({
    "sar": sar_pred,
    "prp": prp_pred,
    "ens": ensemble_pred,
}, index=test_final.index).dropna()

# 2) Por segmento: ejemplo con 'comercial_subchannel_d' (ajusta tu(s) columna(s))
SEG_COLS = ["comercial_subchannel_d"]  # puedes añadir 'prod_key', etc.

# Subset holdout
df_holdout = df[df[DATE_COL].between(test_final.index.min(), test_final.index.max())].copy()

def error_by_group(df_h, group_col, target=TARGET):
    # Real por grupo
    real_g = df_h.groupby([DATE_COL, group_col])[target].sum()
    real_tot = real_g.groupby(level=0).sum()
    # Distribuir las predicciones totales del modelo a cada grupo según “share” histórico (train_full)
    hist = df[df[DATE_COL].lt(test_final.index.min())].copy()
    shares = (hist.groupby([group_col])[target].sum() / hist[target].sum()).replace([np.inf, -np.inf], np.nan).fillna(0.0)
    # pred distribuida por grupo (proporcional a share global histórico)
    pred_ens_by_g = pd.concat([pred_df["ens"]] * len(shares), axis=1)
    pred_ens_by_g.columns = shares.index
    pred_ens_by_g = pred_ens_by_g.mul(shares.values, axis=1)
    # Métrica por grupo (MAE % de su total en holdout)
    out = []
    for g, real_series in real_g.groupby(level=1):
        # Alinear con pred distribuido
        pred_g = pred_ens_by_g[g].reindex(real_series.index.get_level_values(0))
        y_true = real_series.groupby(level=0).sum().reindex(pred_g.index).fillna(0)
        m = metrics_dict(y_true, pred_g)
        out.append({"grupo": g, **m})
    return pd.DataFrame(out).sort_values("MAPE_%", ascending=False)

results_by_seg = {}
for col in SEG_COLS:
    if col in df.columns:
        res = error_by_group(df_holdout, col, target=TARGET)
        results_by_seg[col] = res
        print(f"\n=== Top fallas por {col} (MAPE alto) ===")
        display(res.head(15))

# Variación por fold (ya la tenemos en 'sar_search' y 'prp_search')
print("\n== Estabilidad SARIMA por fold ==")
display(pd.DataFrame(best_sar["folds"]))
print("\n== Estabilidad Prophet por fold ==")
display(pd.DataFrame(best_prp["folds"]))

# Rolling ventanas en el histórico (ej.: MAE de Naive vs Ensemble en ventanas de 28 días)
WIN = 28
roll = []
base = ts.copy()
for start in range(0, len(base)-WIN, WIN):
    win = base.iloc[start:start+WIN]
    if len(win) < WIN: break
    tr = win.iloc[:-SEASON] if len(win) > SEASON+7 else win.iloc[:-7]
    te = win.iloc[-7:]
    if len(tr) == 0 or len(te) == 0: continue
    # usa ensemble entrenado en train_full como proxy (no reentrenamos por ventana para ahorrar tiempo)
    # se evalúa la “estabilidad de error” del modelo fijo en distintos períodos de la serie:
    te_hat = ensemble_pred.reindex(te.index)
    if te_hat.isna().all(): continue
    roll.append({"window_start": win.index.min(), **metrics_dict(te, te_hat)})

roll_df = pd.DataFrame(roll)
print("\n== Estabilidad por ventanas (aprox) ==")
display(roll_df)